// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdktvxZEsq_qMuauQ3hQMqBNx3xxlYjEY',
    appId: '1:1082961399214:web:735a193b765af41463cc3f',
    messagingSenderId: '1082961399214',
    projectId: 'shopper-85642',
    authDomain: 'shopper-85642.firebaseapp.com',
    storageBucket: 'shopper-85642.appspot.com',
    measurementId: 'G-0B376YYRGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ0zCVUXnWn54aHI1OJihEP2p-b8FT6RQ',
    appId: '1:1082961399214:android:1f19cd43d737bee463cc3f',
    messagingSenderId: '1082961399214',
    projectId: 'shopper-85642',
    storageBucket: 'shopper-85642.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP1_bQ7rWwa6yEQ1Txg7QfOqo0NvzO6Qk',
    appId: '1:1082961399214:ios:795ac715f4f4788763cc3f',
    messagingSenderId: '1082961399214',
    projectId: 'shopper-85642',
    storageBucket: 'shopper-85642.appspot.com',
    iosClientId: '1082961399214-jkiu7r6b2qco6fs7ul5e3v9vjtol9hat.apps.googleusercontent.com',
    iosBundleId: 'com.prodroid.shopperMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP1_bQ7rWwa6yEQ1Txg7QfOqo0NvzO6Qk',
    appId: '1:1082961399214:ios:3cb66d7cb8ce5e8d63cc3f',
    messagingSenderId: '1082961399214',
    projectId: 'shopper-85642',
    storageBucket: 'shopper-85642.appspot.com',
    iosClientId: '1082961399214-6kgjpbeqdt6anhvpop69o9p76dtp4k6g.apps.googleusercontent.com',
    iosBundleId: 'com.prodroid.shopperMe.RunnerTests',
  );
}
